import "./globals.css";
import { Suspense } from "react";
import type { Metadata } from "next";
import { Karla } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { Loading } from "@/components/auth/loading";
import { ModalProvider } from "@/providers/modal-provider";
import { ConvexClientProvider } from "@/providers/convex-client-provider";

const font = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Suspense fallback={<Loading />}>
          <ConvexClientProvider>
            <Toaster />
            <ModalProvider />
            {children}
          </ConvexClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
